version: "3"

services:
  back_end:
    image: "{{ back_end_docker_image }}:{{ back_end_docker_tag }}"
    ports:
      - "{{ back_end_port }}:4000"
    environment:
      DATABASE_URL: "postgres://{{ database_username }}:{{ database_password }}@{{ database_uri }}:{{ database_port }}/{{ database_name }}"
      SECRET_KEY_BASE: mum5mF0oA6X3lGgZJWnhKqW/gOzJxagt61BhgyQraXxpYbsqovh2FPsuivUxbAcb
  telegraf:
    image: telegraf:1.16.1
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "{{ monitoring_database_uri }}"
      INFLUXDB_PORT: "{{ monitoring_database_port }}"
      DATABASE: "{{ monitoring_database_name }}"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock