---

- name: Import telegraf.conf
  template:
    src: telegraf.conf
    dest: "{{ database_directory }}/telegraf.conf"
    owner: "{{ database_user }}"
    group: "{{ database_group }}"
  notify: Restart docker compose

- name: Import docker-compose
  template:
    src: docker-compose.yml
    dest: "{{ database_directory }}/docker-compose.yml"
    owner: "{{ database_user }}"
    group: "{{ database_group }}"
  notify: Restart docker compose

- name: Start docker-compose
  docker_compose:
    project_src: "{{ database_directory }}"