version: "3"

services:
  client:
    image: amauryfaveriel/time-manager-client:0.1
    ports:
      - 80:80
  server:
    image: amauryfaveriel/time-manager-server:0.1
    restart: always
    depends_on:
      - database
    ports:
      - 4000:4000
    networks:
      - backend
  database:
    image: postgres:13.0
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: theme_01_dev

networks:
  backend:
  tig-net: