version: "3"

services:
  database:
    image: "{{ database_docker_image }}:{{ database_docker_tag }}"
    ports:
      - "{{ database_port }}:5432"
    volumes:
    - ./files:/data
    environment:
      POSTGRES_USER: "{{ database_username }}"
      POSTGRES_PASSWORD: "{{ database_password }}"
      POSTGRES_DB: "{{ database_name }}"
  telegraf:
    image: telegraf:1.16.1
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "{{ monitoring_database_uri }}"
      INFLUXDB_PORT: "{{ monitoring_database_port }}"
      DATABASE: "{{ monitoring_database_name }}"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock