---

- name: Import docker-compose
  template:
    src: docker-compose.yml
    dest: "{{ monitoring_directory }}/docker-compose.yml"
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_group }}"
  notify: Restart docker compose

- name: Start docker-compose
  docker_compose:
    project_src: "{{ monitoring_directory }}"
    