version: "3"

services:
  client:
    image: "{{ client_docker_image }}:{{ client_docker_tag }}"
    ports:
      - "{{ client_port }}:80"
  telegraf:
    image: telegraf:1.16.1
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "{{ monitoring_database_uri }}"
      INFLUXDB_PORT: "{{ monitoring_database_port }}"
      DATABASE: "{{ monitoring_database_name }}"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock